-- descriptions-update.sql
-- 72 praias sem description → UPDATE statements
-- Gerado em: 2026-03-31
-- INSTRUÇÃO: colar no SQL Editor do Supabase e clicar RUN
-- Sem deploy. Sem execução automática.

-- ═══════════════════════════════════════════════
-- ALENTEJO (10)
-- ═══════════════════════════════════════════════

UPDATE beaches SET description = 'Encravada numa enseada rochosa protegida por falésias escuras e perfis abruptos, a Praia da Arrifana faz parte do litoral bravio da Costa Vicentina. A qualidade da água é Boa, e a praia tem carácter surf — as condições atlânticas são frequentes e atraem praticantes durante grande parte do ano. O acesso desce até ao areal através de um caminho que corta a falésia, revelando o Atlântico gradualmente. É uma praia de escala humana, sem a afluência das praias mais conhecidas do Algarve vizinho.' WHERE id = 'a6625ef3-a4ad-4e38-b74e-856ffc9fa724';

UPDATE beaches SET description = 'A Praia de Monte Clérigo fica na costa noroeste do Algarve, já dentro do território da Costa Vicentina — um litoral protegido onde a densidade urbanística é baixa e o carácter natural prevalece. A qualidade da água é Boa. O areal é de dimensão média, emoldurado por dunas e falésia baixa, com ondulação atlântica regular que atrai surfistas e bodyboarders. A proximidade a Aljezur torna-a acessível, mas mantém a quietude típica deste trecho de costa.' WHERE id = 'e1e260e4-5094-4dee-8c90-11a43523e126';

UPDATE beaches SET description = 'A Praia de Odeceixe é um dos casos mais singulares da costa portuguesa — a ribeira de Seixe separa a praia do rio do areal oceânico, criando dois ambientes distintos num único espaço: água doce e água atlântica, correntes calmas e ondulação aberta. A qualidade da água é Boa. A praia fica no limite entre o Alentejo e o Algarve, dentro do Parque Natural do Sudoeste Alentejano e Costa Vicentina. O areal é protegido pelos montes envolventes, o que reduz o impacto do vento e cria uma atmosfera de vale junto ao mar.' WHERE id = 'c627b1c9-8467-4729-aa26-15fb6e86e6af';

UPDATE beaches SET description = 'A Praia de São Torpes situa-se a sul de Sines, numa zona de transição entre o litoral industrial do porto e o início da costa alentejana mais selvagem. A qualidade da água é Boa. O areal é extenso e de acesso relativamente fácil, com dunas estabilizadas por vegetação costeira. As condições de ondulação tornam-na popular entre surfistas, e o vento sul-atlântico frequente atrai também a prática de windsurf. É uma praia com horizonte aberto e poucos obstáculos visuais — o tipo de faixa costeira rara nas proximidades de um centro industrial.' WHERE id = 'dee27f4d-ec13-43b4-a618-4ac272d22cf2';

UPDATE beaches SET description = 'A Praia de Tróia fica na Península de Tróia, uma faixa de areia que separa o Estuário do Sado do Atlântico, acessível de Setúbal por ferry. O areal atlântico é longo, com ondulação aberta e qualidade da água Boa. Do lado oposto, as margens voltadas para o estuário oferecem um contraste com água calma e condições diferentes. A travessia de barco sobre o Sado — onde há registos regulares de avistamento de golfinhos — faz parte da experiência de visitar Tróia. A península tem escala suficiente para absorver os visitantes de verão sem perder o carácter natural das zonas mais afastadas da marina.' WHERE id = '0b9d2380-38cf-437d-a4e3-4b68158ba2a4';

UPDATE beaches SET description = 'A Praia de Vila Nova de Milfontes fica na foz do Rio Mira, onde as águas do rio e o Atlântico se encontram a separar o areal da vila histórica. A qualidade da água é Boa. Esta é uma das localidades mais apreciadas da costa alentejana — a escala contida da vila, as casas brancas e a presença do rio conferem-lhe um carácter que não se encontra nas praias de resort. O areal é protegido e adequado para famílias, com o mar atlântico acessível um pouco mais a sul. Milfontes é frequentemente referida como uma das melhores vilas de praia em Portugal — e raramente desilude quem chega pela primeira vez.' WHERE id = '2dd735c3-9317-45bb-aed7-c3832af7653d';

UPDATE beaches SET description = 'A Praia do Almograve é uma praia de carácter marcado pelo enquadramento geológico: plataformas rochosas, lajes e piscinas naturais coexistem com o areal estreito, compondo um litoral de textura visual densa. A qualidade da água é Boa. Insere-se na Costa Vicentina, numa zona de baixa pressão turística onde a paisagem é determinada pelas forças naturais, não pela infraestrutura. A ondulação atlântica, as formações rochosas e a luz do fim do dia sobre as lajes tornam esta praia especialmente apelativa para fotografia e exploração à maré baixa.' WHERE id = '6b2661a4-4126-4ac4-8a03-ec2193cd4494';

UPDATE beaches SET description = 'A Praia do Amado é uma das referências do surf na Costa Vicentina — um areal amplo exposto à ondulação atlântica, sem barreiras naturais que atenuem as condições de vento e mar. A qualidade da água é Boa. A praia fica dentro do Parque Natural do Sudoeste Alentejano e Costa Vicentina, o que limita a construção e preserva o carácter aberto do lugar. Fora das épocas de maior ondulação, o areal extenso e a imensidão do horizonte atlântico tornam-na uma praia com personalidade própria, ainda que com menos infraestrutura do que as praias mais a sul.' WHERE id = 'b04adbca-20fc-44e0-b947-066978b8fffc';

UPDATE beaches SET description = 'A Praia do Carvalhal fica na orla costeira da região de Grândola, entre pinheiros e dunas baixas que chegam quase até à berma do areal. A qualidade da água é Boa. É uma praia de costa alentejana por excelência: longa, de areia clara, com poucos elementos construídos na linha de frente e uma quietude que persiste mesmo nos meses de maior afluência. A vegetação dunar e o pinhal que bordeja o acesso criam um corredor natural que precede a chegada ao oceano — um ritual de chegada que faz parte da experiência da praia.' WHERE id = 'f940e21f-3169-486c-9438-30dd3e503eb3';

UPDATE beaches SET description = 'Zambujeira do Mar é uma das praias mais bem resguardadas da Costa Vicentina — o areal encaixa entre falésias altas que bloqueiam o vento e criam uma sensação de reclusão quase teatral. A qualidade da água é Boa. O acesso é feito por uma descida entre a falésia e a vegetação costeira que precede a chegada ao oceano de forma gradual. A praia é também conhecida pela realização do festival de música Sudowest NOS, que transforma o anfiteatro natural das falésias num dos cenários de festival ao ar livre mais singulares do país. Fora da época do festival, Zambujeira é uma praia de surf com identidade rural e carácter próprio.' WHERE id = '4bd3bca5-6c5b-486d-87c0-bd21ea5435ce';

-- ═══════════════════════════════════════════════
-- ALGARVE (14)
-- ═══════════════════════════════════════════════

UPDATE beaches SET description = 'A Meia Praia estende-se por vários quilómetros a leste de Lagos, numa das faixas de areal mais compridas do barlavento algarvio. A qualidade da água é Excelente. Ao contrário das praias de enseada encaixadas entre falésias da zona, a Meia Praia tem dimensão e abertura que permitem absorver visitantes sem perder o espaço de praia. Do areal avista-se a cidade de Lagos e a foz do Rio Bensafrim. É uma alternativa de escala diferente às praias rochosas da costa de Lagos — ideal para quem procura extensão de areal, acesso fácil e água de qualidade.' WHERE id = '9b62bea8-e8c4-44f1-9ab5-9e9864cf6bb5';

UPDATE beaches SET description = 'A Praia da Altura situa-se no sotavento algarvio, perto da fronteira com Espanha, numa zona de menor densidade turística do que o Algarve central. A qualidade da água é Excelente. O areal é longo e de areia fina, com acesso pela vila de Altura, que mantém dimensão contida. A ausência das formações rochosas características das praias mais a oeste é compensada pela tranquilidade e pela extensão de costa. Para quem visita o sotavento algarvio, a Praia da Altura é uma opção com boa qualidade balnear e menos pressão do que as praias do Algarve central.' WHERE id = 'efdfab6a-36b9-42a6-8e11-019450a51c86';

UPDATE beaches SET description = 'A Praia da Galé fica a poente de Albufeira, já fora da área de maior concentração urbana, numa secção de costa com falésias de calcário e areia branca. A qualidade da água é Excelente. O areal é bem dimensionado e a exposição solar ao longo do dia é generosa — características que a tornam popular durante o verão. As falésias baixas que limitam o areal oferecem alguma proteção ao vento e enquadram visualmente a praia de forma agradável. É uma das praias da zona de Albufeira que combina boa acessibilidade com carácter natural mais definido do que as praias urbanas da cidade.' WHERE id = '59de93aa-066b-4d01-9c4e-27f3a40422f1';

UPDATE beaches SET description = 'A Praia da Luz é a praia da vila com o mesmo nome, a alguns quilómetros a oeste de Lagos. O areal é de dimensão média, emoldurado por falésias escuras de rocha basáltica que contrastam com a areia clara — uma composição visual diferente da maioria das praias algarvias. A qualidade da água é Excelente. A vila de Luz tem escala humana, com comércio e restauração a poucos passos do areal. A Rocha Negra — uma formação rochosa proeminente num extremo da praia — é um dos elementos visuais mais reconhecíveis de toda a costa de Lagos.' WHERE id = '4325b4a7-62f3-46a7-a66d-ae0ad6e0d374';

UPDATE beaches SET description = 'A Praia da Senhora da Rocha fica entre Armação de Pêra e Porches, numa enseada delimitada por falésias de calcário com uma pequena ermida no promontório que avança para o mar. A qualidade da água é Excelente. A praia divide-se em duas secções separadas por um recorte da falésia, com carácter mais resguardado do que as praias abertas da zona. A ermida no topo — uma das imagens de postal mais reconhecíveis desta parte do Algarve — é acessível por um percurso na falésia com vistas sobre ambos os areais.' WHERE id = '6cafdc55-fcea-4e55-b2a1-78995f44b609';

UPDATE beaches SET description = 'A Praia de Alvor fica na embocadura da ria de Alvor, onde o estuário de águas calmas encontra o Atlântico aberto. O areal é extenso e de areia fina, com qualidade da água Excelente, e a ria oferece zonas de banho mais calmas para famílias e crianças. A vila de Alvor, a poucos minutos, mantém carácter genuinamente piscatório — com barcos de pesca, marisqueiras e um ambiente menos focado no turismo de resort do que a vizinha Portimão. O percurso ao longo das salinas e do estuário até ao areal é um dos trajetos mais agradáveis desta zona do Algarve.' WHERE id = '925ac239-db1f-432b-98ee-7a308ae9a6b8';

UPDATE beaches SET description = 'A Praia de Armação de Pêra é uma das praias mais compridas do Algarve central — um areal extenso e bem equipado, diretamente ligado à frente de mar da localidade. A qualidade da água é Excelente. A praia tem carácter urbano com toda a infraestrutura de suporte disponível nas imediações. Para além do areal principal, a costa adjacente oferece acesso a algumas das grutas e formações rochosas mais fotografadas do Algarve central. É uma praia com capacidade para absorver grande afluência, o que a torna popular entre famílias e viajantes em grupo.' WHERE id = 'd723c15c-6b6b-4c47-8182-c06313e0e641';

UPDATE beaches SET description = 'A Praia de Faro fica numa ilha-barreira da Ria Formosa, acessível por ponte ou de barco a partir da cidade de Faro. O areal atlântico é longo e aberto, com qualidade da água Excelente — um dos maiores contrastes possíveis com a paisagem urbana de Faro a poucos minutos. A Ria Formosa, visível do lado interior da ilha, tem o carácter distinto de uma laguna — fauna avifaunística diversa, água calma e a geometria das salinas que percorrem o parque natural. Para os habitantes de Faro, é a saída de mar mais próxima da cidade — e uma das mais acessíveis de todo o Algarve.' WHERE id = '4b75fb06-7715-4b56-8b37-8f6eb332ae22';

UPDATE beaches SET description = 'A Praia de Ferragudo fica na margem sul do estuário do Rio Arade, com vista direta para a Praia da Rocha e para a cidade de Portimão. O areal é de dimensão média, com qualidade da água Excelente e uma vila piscatória imediatamente atrás — com barcos de pesca, uma pequena fortaleza medieval e restauração de carácter genuíno. É frequentemente preferida à Praia da Rocha por quem procura o mesmo nível de conforto com menos afluência. A vista sobre o estuário e a costa de Portimão, especialmente ao final do dia, é um dos enquadramentos mais distintos desta zona do Algarve.' WHERE id = '0e3bf570-263f-45c1-afd2-0f9ca232b07c';

UPDATE beaches SET description = 'A Praia de Vilamoura situa-se junto ao complexo de marina que deu nome a um dos maiores centros turísticos do Algarve. O areal é extenso, de areia fina, com qualidade da água Excelente. A organização e os serviços de suporte estão entre os mais completos da região. A marina adjacente, com a sua concentração de embarcações e comércio de posicionamento premium, confere à praia um contexto diferente das praias de falésia mais selvagens do barlavento. É uma escolha coerente para quem prioriza conforto e fácil acesso a partir de um alojamento na zona.' WHERE id = '8c523fc0-993c-4e0e-9d29-755d7257be50';

UPDATE beaches SET description = 'A Praia do Camilo é uma das menores e mais fotogénicas do barlavento algarvio — um recanto de areia entre falésias de calcário esculpidas em formas orgânicas que parecem desafiar a escala humana. A qualidade da água é Excelente. O acesso é feito por uma escada de madeira que desce pela falésia, o que mantém a afluência mais controlada do que nas praias de acesso fácil. As formações rochosas circundantes criam piscinas naturais e enquadramentos que a tornam popular para fotografia. É uma praia complementar às praias de maior dimensão de Lagos — mais adequada para quem procura recolhimento do que espaço.' WHERE id = 'd9af39d6-f9ae-483d-ab1d-e48a026dfd53';

UPDATE beaches SET description = 'A Praia do Peneco é a praia mais próxima do centro histórico de Albufeira, acessível a pé a partir da vila velha por um túnel que atravessa a falésia. A qualidade da água é Excelente. O areal é de dimensão contida e tem carácter urbano, com a densidade de Albufeira imediatamente atrás. Apesar da proximidade ao centro, as falésias que a envolvem criam um recorte visual que a distingue das praias de areal aberto da zona. É uma praia de conveniência para quem se aloja na área da vila velha — e uma das entradas mais diretas ao mar desta parte do Algarve.' WHERE id = '084b12c9-a27a-4865-98b4-6932918e3609';

UPDATE beaches SET description = 'A Praia do Vau situa-se a poente da Praia da Rocha, numa secção de costa com menor densidade urbana e um carácter mais recortado pelas falésias de calcário. A qualidade da água é Excelente. O areal é de dimensão moderada e as formações rochosas que o limitam criam algum resguardo natural. É frequentemente escolhida como alternativa mais tranquila à vizinha Praia da Rocha — a que acumula maior afluência do barlavento de Portimão. O percurso costeiro entre ambas as praias, ao longo do topo da falésia, oferece vistas sobre as formações rochosas desta secção do Algarve.' WHERE id = '885a3c2e-2f8d-424d-b98c-a8c7b8732bee';

UPDATE beaches SET description = 'A Praia Verde fica no sotavento algarvio, perto de Castro Marim, numa zona onde o pinhal se aproxima da praia e o horizonte costeiro permanece aberto. A qualidade da água é Excelente. O nome descreve o enquadramento: vegetação costeira densa em contraste com o areal claro e a água de tonalidade que oscila entre o verde e o azul consoante a luz. É uma das praias mais tranquilas desta zona do Algarve — com menos turismo de massa do que as praias a ocidente — e mantém o carácter de praia de pinhal que raramente se encontra noutros pontos do litoral algarvio.' WHERE id = 'feead871-bb63-43d7-acf9-592d7d54b514';

-- ═══════════════════════════════════════════════
-- CENTRO (16)
-- ═══════════════════════════════════════════════

UPDATE beaches SET description = 'A Praia da Areia Branca fica na costa da Lourinhã, uma zona da Estremadura portuguesa conhecida também pelos seus achados paleontológicos. O areal é generoso e de acesso fácil, com qualidade da água Boa e exposição atlântica que gera ondulação propícia ao surf. A falésia que ladeia parte do areal tem composição sedimentar que atrai visitantes com interesse geológico, para além dos banhistas habituais. É uma praia da Estremadura que combina boas condições balneares com um contexto territorial de interesse.' WHERE id = 'fd1474e1-7acb-4635-822d-df649332769e';

UPDATE beaches SET description = 'A Praia da Barra fica na embocadura da Ria de Aveiro, junto ao canal que liga a laguna ao Atlântico — e é identificada de longe pelo farol listrado de vermelho e branco, um dos mais altos de Portugal. A qualidade da água é Boa. O areal é extenso e as correntes da embocadura conferem dinamismo às condições de mar. A Ria de Aveiro, visível do outro lado do canal, oferece um contraponto de águas calmas à ondulação atlântica da praia. É uma das praias de referência da costa de Aveiro, com fácil acesso a partir da cidade e do complexo lagunar.' WHERE id = '47af766c-c76f-483f-986b-5dbefd6f294a';

UPDATE beaches SET description = 'A Praia da Costa Nova é inseparável das palheiros — as casas de madeira com riscas verticais coloridas que alinham a frente de mar e são um dos cenários mais reconhecíveis da costa de Aveiro. A qualidade da água é Boa. O areal é largo e exposto à ondulação atlântica, com condições que atraem surfistas e bodyboarders. Do lado da ria, a paisagem muda completamente: água calma, barcos moliceiros e a geometria dos canais que caracterizam o Parque Natural da Ria de Aveiro. É uma praia com identidade visual forte e uma das mais fotografadas da Beira Litoral.' WHERE id = '26b8762d-0343-4a93-9670-9a86993e7dfd';

UPDATE beaches SET description = 'A Praia da Figueira da Foz é um dos grandes areais urbanos da costa atlântica portuguesa — uma faixa extensa que enquadra a frente de mar de uma das cidades costeiras mais dinâmicas da Beira Litoral. A qualidade da água é Boa. A praia tem boa infraestrutura de suporte, fácil acesso e é um ponto de convergência de famílias, grupos de jovens e surfistas que aproveitam a ondulação regular do Atlântico. O casino da cidade, visível da frente de mar, é um dos elementos arquitetónicos mais marcantes da Figueira — parte de uma herança balnear com raízes no século XIX.' WHERE id = '07b0b2c3-f11d-474d-9f5f-02dc87a4be64';

UPDATE beaches SET description = 'A Praia da Foz do Arelho tem dois lados distintos: o areal atlântico, com ondulação e qualidade da água Boa, e a Lagoa de Óbidos, uma laguna de água calma que permite atividades náuticas sem ondas. A fronteira entre os dois ambientes muda consoante as marés e as condições do canal de entrada. A lagoa é particularmente popular para prancha e kayak. O conjunto — mar aberto num lado, laguna no outro — torna a Foz do Arelho uma das praias com maior diversidade de condições da costa da Estremadura.' WHERE id = 'fefd19c5-2dad-4627-a476-daa13be99352';

UPDATE beaches SET description = 'A Praia da Murtinheira situa-se a norte da Figueira da Foz, numa secção da costa de Aveiro onde os areais se sucedem com espaçamento regular e afluência mais baixa do que nas praias principais. A qualidade da água é Boa. O areal é amplo e exposto à ondulação atlântica, com dunas costeiras que marcam a transição entre o pinhal e a praia. É uma praia de carácter mais tranquilo do que os seus vizinhos mais populares — adequada para quem procura o litoral da Beira sem a densidade das praias de maior referência.' WHERE id = 'b5d5f332-d553-49d9-ad92-77d658de945f';

UPDATE beaches SET description = 'A Praia da Tocha fica no litoral de Cantanhede, entre Aveiro e a Figueira da Foz, numa zona onde o pinhal litoral chega muito próximo do areal. A qualidade da água é Boa. É uma praia de identidade costeira tradicional: areal extenso, ondulação atlântica, dunas com vegetação rasteira e um ambiente menos urbano do que as praias de maior afluência da região. Os veraneantes que regressam ano após ano conhecem o seu carácter — uma praia de costa atlântica sem artificialidade, com o pinhal sempre próximo.' WHERE id = 'f400d000-20b2-414c-ba38-bae63856431f';

UPDATE beaches SET description = 'A Praia da Torreira fica na margem exterior da Ria de Aveiro, numa língua de terra que separa a laguna do Atlântico. A qualidade da água é Boa. A posição geográfica é única: de um lado, a imensidão do oceano com ondulação aberta; do outro, a quietude da ria e a fauna das reservas naturais do parque. A Torreira é um ponto de partida habitual para excursões de barco pela Ria de Aveiro. A praia principal tem extensão suficiente para absorver visitantes e as condições de mar são características do litoral atlântico norte.' WHERE id = 'e5113c93-c469-489a-8db6-7d877c0de22c';

UPDATE beaches SET description = 'A Praia da Vagueira situa-se a sul de Aveiro, numa secção da costa da Beira Litoral com areais extensos e condições de ondulação que marcam o perfil desta faixa costeira. A qualidade da água é Boa. A localidade da Vagueira tem uma relação de longa data com o mar — e também com a vulnerabilidade do litoral atlântico, num trecho onde a erosão costeira é um tema recorrente. Para além das condições balneares, a praia é frequentada por surfistas e os seus areais extensos são adequados para longas caminhadas costeiras.' WHERE id = '6b3928b3-4680-4051-b2f1-e3bdb41cab35';

UPDATE beaches SET description = 'A Praia da Vieira de Leiria fica no litoral de Marinha Grande, numa zona onde o pinhal de Leiria — uma das florestas costeiras mais antigas de Portugal — bordeja os acessos à praia. A qualidade da água é Boa. O areal é extenso e a ondulação atlântica tem dimensão que atrai surfistas. A vila de Vieira de Leiria tem identidade própria, com raízes piscatórias que coexistem com o turismo balnear sazonal. A sombra do pinhal e a frescura dos acessos arborizados tornam a chegada à praia num dos melhores aspectos de visitar esta costa.' WHERE id = '885d20c0-e362-4825-b250-b63ffaaf9631';

UPDATE beaches SET description = 'A Praia de Buarcos fica a norte da Figueira da Foz, junto ao bairro de pescadores com o mesmo nome — uma das comunidades costeiras mais antigas desta secção da Beira Litoral. A qualidade da água é Boa. A praia tem carácter mais local do que as praias de areal aberto da Figueira, com as embarcações de pesca a contrastar com as infraestruturas balneares. A presença do Buarcos histórico imediatamente atrás dá contexto ao lugar — é uma praia onde a vida marítima quotidiana e o veraneio balnear partilham o mesmo espaço sem conflito.' WHERE id = '63806db3-12a1-4e83-b354-1ac4b44fcb2d';

UPDATE beaches SET description = 'A Praia de Mira fica no litoral de Mira, com a Lagoa de Mira como fundo imediato — uma laguna costeira separada do oceano pelas dunas que criam uma zona de transição entre dois tipos de paisagem. A qualidade da água é Boa. A praia atlântica tem extensão e exposição características desta costa, com condições que agradam tanto a banhistas como a surfistas. A lagoa, acessível a pé, oferece águas calmas para quem prefere ambiente sem ondulação. O pinhal que enquadra os acessos é uma constante desta costa — e Mira não é exceção.' WHERE id = 'd762875e-3d8a-467c-bb1b-efed5b1c42d0';

UPDATE beaches SET description = 'A zona de Peniche concentra algumas das melhores ondas de Portugal numa só área geográfica — e a Praia de Peniche, exposta à ondulação atlântica frontal, é parte central dessa reputação. A qualidade da água é Boa. A cidade ocupa um promontório rochoso que avança para o Atlântico, o que lhe confere uma relação com o mar particularmente intensa. A Fortaleza de Peniche e a proximidade à Reserva Natural da Berlenga — a alguns quilómetros ao largo — tornam Peniche uma das paragens mais completas da costa da Estremadura.' WHERE id = 'ffe1a91f-de57-4ff0-9ad5-d32951851730';

UPDATE beaches SET description = 'A Praia de S. Pedro de Moel fica encaixada entre o pinhal de Leiria e o Atlântico, num troço da costa de Marinha Grande onde a floresta costeira chega próxima do areal. A qualidade da água é Boa. A localidade tem uma história balnear com raízes nos finais do século XIX, e a arquitetura das casas de veraneio que pontilham o pinhal reflete esse passado. O areal é parcialmente protegido por uma reentrância da costa que oferece algum resguardo em relação ao vento norte. É uma praia com personalidade reconhecível — o cheiro a pinheiro, a textura da areia e a luz filtrada pelo pinhal antes de chegar à praia.' WHERE id = '24dba43c-02fb-40bc-b3a8-d39e1f8ea49e';

UPDATE beaches SET description = 'A Praia de São Martinho do Porto é singular no contexto da costa atlântica portuguesa: a baía em forma de concha praticamente fechada transforma o que seria um areal atlântico exposto num ambiente de águas calmas, quentes no verão e protegido do vento e da ondulação. A qualidade da água é Boa. A forma da baía — com a entrada estreita voltada a sul — cria condições únicas para famílias e crianças. A vila de São Martinho do Porto, com a frente de mar construída sobre a baía, adiciona escala humana ao conjunto. É uma das praias mais genuinamente diferentes de toda a costa da Estremadura.' WHERE id = '6347e27e-d7fe-45bd-9fb8-ff3d7557d100';

UPDATE beaches SET description = 'A Praia do Pedrógão situa-se no litoral de Leiria, entre Vieira de Leiria e a Figueira da Foz, numa secção de costa atlântica aberta com areais extensos e ondulação franca. A qualidade da água é Boa. A localidade tem dimensão de vila balnear consolidada, com uma frente de mar que concentra serviços de apoio à praia durante a época de verão. O areal largo e a ondulação regular atraem surfistas, e os pinhais que acompanham os acessos reforçam o carácter desta costa. É uma praia da Beira Litoral com boa relação entre dimensão, serviço e carácter costeiro.' WHERE id = 'c4bea301-56f1-49b5-934d-f576e41f5132';

-- ═══════════════════════════════════════════════
-- LISBOA E SETÚBAL (3)
-- ═══════════════════════════════════════════════

UPDATE beaches SET description = 'A Praia de Cascais é a praia da vila — um areal urbano e acessível que fica a poucos minutos a pé do centro histórico de Cascais e da sua marina. A qualidade da água é Boa. A praia tem dimensão contida mas bem localizada, com a baía de Cascais a criar alguma proteção em relação à ondulação aberta do Atlântico. A possibilidade de combinar praia, centro histórico e marina num único passeio é um dos atrativos da visita a Cascais. Para sessões mais longas de praia, as praias adjacentes oferecem mais espaço — mas a Praia de Cascais tem a vantagem imbatível da conveniência e da escala humana da vila.' WHERE id = 'fede421d-0f75-46f7-9248-9a374bc63c4c';

UPDATE beaches SET description = 'A Praia de Sesimbra é uma das praias mais protegidas da costa a sul de Lisboa — a baía onde o areal se instala é abraçada por serras baixas que bloqueiam o vento dominante e criam condições de mar geralmente mais calmas do que o resto do litoral. A qualidade da água é Boa. A vila de Sesimbra, construída sobre o morro que olha para a baía, tem carácter piscatório genuíno — com barcos de pesca, a fortaleza no topo e restauração de marisco que persiste para além da sazonalidade turística. É uma das escapadas preferidas de Lisboa para quem quer praia com vila, não apenas areal.' WHERE id = '9efe4cc6-cb4a-4265-83c3-c710917810c1';

UPDATE beaches SET description = 'A Praia de Setúbal situa-se no contexto urbano da cidade de Setúbal, à entrada do estuário do Sado e com a Serra da Arrábida como pano de fundo próximo. A qualidade da água é Boa. É uma praia de acesso conveniente para quem reside na cidade — não tem a escala de resort das praias da Arrábida, mas oferece o mar a distância de calçada. A cidade de Setúbal, com o seu mercado de peixe e a frente ribeirinha, é um ponto de partida excelente para explorar esta costa. Para praias de água verdejante e falésias calcárias, as praias da Arrábida ficam a poucos minutos de estrada.' WHERE id = 'd8c2c61e-734a-41c5-aec1-66981023cfca';

-- ═══════════════════════════════════════════════
-- MADEIRA (5)
-- ═══════════════════════════════════════════════

UPDATE beaches SET description = 'A Fajã da Areia é uma fajã do norte da Ilha da Madeira, formada por uma plataforma de lava que avança para o oceano e cria um espaço de contacto com o mar de carácter muito próprio. A qualidade da água é Boa. O acesso requer deslocação deliberada e o enquadramento é o de costa atlântica crua — sem qualquer mediação com o oceano norte. O contraste entre a lava escura, a vegetação de falésia e o azul profundo do Atlântico é uma composição visual marcante. É uma das fajãs menos acessíveis da Madeira — o que contribui para a sua quietude e preservação.' WHERE id = 'aa950882-863f-42db-81b8-0c5e9d64ba24';

UPDATE beaches SET description = 'O Jardim do Mar é uma das mais pequenas e mais carismáticas localidades costeiras da Madeira — uma aldeia na falésia sul da ilha, com casas voltadas para o Atlântico e um dos melhores pontos de surf da ilha imediatamente em frente. A qualidade da água é Boa. A costa junto ao Jardim do Mar, formada por lava e açoreamentos naturais, tem ondas que atraem surfistas de vários pontos da Europa nos meses de inverno. A aldeia mantém dimensão e carácter muito contidos, e a estrada de acesso que serpenteia pela falésia faz da chegada uma parte da experiência.' WHERE id = 'ebf82db0-f4b2-4bb7-a1fb-ec6f07e90632';

UPDATE beaches SET description = 'O Paul do Mar é uma aldeia piscatória encravada entre a falésia sul da Madeira e o Atlântico — num espaço estreito onde as casas ficam literalmente entre a rocha e o mar. A qualidade da água é Boa. A costa aqui é de lava e calhau, sem areia de praia convencional, mas com piscinas naturais entre as rochas que são o ponto de mergulho e banho da comunidade. É uma aldeia com identidade muito própria, marcada pela pesca e pela posição geográfica excecional. Para quem visita o sudoeste da Madeira, Paul do Mar é uma paragem que transmite a escala humana da ilha de forma direta.' WHERE id = 'fdf3f8dc-a8e9-491e-9c9e-4bea8bb8fa47';

UPDATE beaches SET description = 'A Praia de Porto Santo é uma das referências de areia atlântica no arquipélago da Madeira — uma faixa de vários quilómetros de areia clara, quente e de granulometria fina que ocupa quase toda a costa sul da ilha de Porto Santo. A qualidade da água é Excelente. A areia de Porto Santo tem composição mineral reconhecida, com propriedades terapêuticas atribuídas a elementos que a distinguem de areais comuns. A ilha tem escala humana e ritmo tranquilo, muito diferente da Madeira: menos vegetação exuberante, mais luz, mais vento e um Atlântico de tonalidade turquesa no verão que raramente defrauda.' WHERE id = 'de8ce91b-729b-451d-9eac-1eedd1d62790';

UPDATE beaches SET description = 'A Praia do Seixal é uma das praias mais conhecidas do norte da Madeira — um areal de calhau e areia escura num anfiteatro natural formado por falésias altas de basalto, com uma cascata que desce diretamente sobre a praia em períodos de maior caudal. A qualidade da água é Boa. A costa norte da Madeira tem ondulação atlântica mais intensa do que o sul, o que cria condições de banho variáveis consoante a estação. As piscinas naturais adjacentes oferecem alternativa em dias de mar agitado. O enquadramento paisagístico — entre falésias de lava e o oceano aberto — é um dos mais dramáticos de todo o arquipélago.' WHERE id = 'b7c02df5-a01e-40e3-8a13-342d56058eb4';

-- ═══════════════════════════════════════════════
-- NORTE (12)
-- ═══════════════════════════════════════════════

UPDATE beaches SET description = 'A Praia das Caxinas fica em Vila do Conde, associada à comunidade piscatória que lhe dá o nome — uma das mais activas da costa norte de Portugal. A qualidade da água é Boa. O areal tem carácter local e a presença da pesca artesanal — com embarcações, artes de pesca e a actividade do porto — confere-lhe uma autenticidade que as praias mais turísticas raramente conseguem. A frente de mar de Vila do Conde, com o mosteiro e a ponte histórica ao fundo, é um enquadramento que distingue esta zona da costa do Minho e do Douro.' WHERE id = 'f7fa6d81-2872-4971-be81-42464b11ac9f';

UPDATE beaches SET description = 'A Praia de Apúlia, em Esposende, é conhecida pelas suas formações rochosas que emergem do areal durante a maré baixa, criando um cenário irregular e visualmente interessante. A qualidade da água é Boa. As dunas da Apúlia fazem parte do sistema dunar do Parque Natural do Litoral Norte, uma reserva que protege este trecho de costa. A ondulação atlântica, frequente e de dimensão considerável, atrai surfistas. É uma praia de carácter norte-atlântico puro: vento, areia, rochas e a linha do horizonte sem interferência — um tipo de costa que vai ficando mais raro ao longo do litoral português.' WHERE id = '51c5eb21-e534-4c5c-98e0-305c78721686';

UPDATE beaches SET description = 'A Praia de Esmoriz fica no limite norte do concelho de Ovar, numa costa plana e extensa que marca o início do litoral da Beira Litoral. A qualidade da água é Boa. O areal é largo e de areia clara, com a ondulação atlântica que caracteriza toda esta faixa da costa norte. A localidade tem identidade própria — com raízes piscatórias e uma comunidade estável que complementa o veraneio sazonal. É uma praia sem a visibilidade das suas vizinhas Espinho ou Matosinhos, mas com carácter de vila balnear que persiste ao longo do ano.' WHERE id = 'db7e9098-4293-4b44-a443-d42491916a91';

UPDATE beaches SET description = 'A Praia de Espinho é a praia de uma das cidades balneares mais emblemáticas da costa norte — uma cidade fundada sobre a areia, com uma frente de mar definida e uma relação com o Atlântico que remonta às primeiras décadas do turismo balnear em Portugal. A qualidade da água é Boa. A ondulação atlântica é constante e a praia é frequentada por surfistas e por banhistas da grande área do Porto. O casino e a infraestrutura urbana de Espinho são parte de uma herança balnear que posiciona a cidade como praia com história e carácter urbano consolidado.' WHERE id = '63d09050-d513-474a-87f4-3658b18da09a';

UPDATE beaches SET description = 'A Praia de Esposende fica na foz do Rio Cávado, onde o estuário cria uma área de transição entre a água do rio e o Atlântico. A qualidade da água é Boa. A praia tem o carácter desta costa do Minho: areia clara, vento frequente, ondulação atlântica franca e um horizonte sem interrupções. A cidade de Esposende, com a sua frente de mar e o enquadramento do farol, é uma das mais acessíveis para visitar nesta secção do litoral. O estuário do Cávado — visível a partir da praia — faz parte do Parque Natural do Litoral Norte.' WHERE id = '6adf3ccd-9fd2-4bc0-894e-e4c775fb3e71';

UPDATE beaches SET description = 'A Praia de Leça da Palmeira fica no concelho de Matosinhos, a norte do Porto, conhecida também pelas Piscinas das Marés — uma obra do arquiteto Álvaro Siza Vieira integrada nas rochas costeiras que é referência internacional da arquitetura do século XX. A qualidade da água é Boa. O areal é adjacente às piscinas e a praia combina banho atlântico com a possibilidade de nadar nas piscinas em dias de mar mais agitado. A costa de Leça tem carácter marcado pelas formações rochosas que afloram do areal e pelo contexto portuário que define esta entrada norte do Porto.' WHERE id = '62030703-6711-4653-bc35-b1284f35cd5e';

UPDATE beaches SET description = 'A Praia de Matosinhos é a praia mais acessível do Porto — areal urbano, de dimensão generosa, com ligação direta à cidade por metro e a escassos minutos do centro. A qualidade da água é Boa. A ondulação atlântica é regular e a praia atrai surfistas com frequência. Matosinhos é também conhecida pela concentração de restaurantes de marisco e peixe fresco que tornam qualquer refeição depois da praia uma extensão natural da visita. É uma praia de cidade — com tudo o que isso implica de conveniência e animação — sem a frieza estética das praias puramente urbanas.' WHERE id = '9fd20503-ced1-4e4c-9069-d38c320ef247';

UPDATE beaches SET description = 'A Praia de Moledo fica no extremo norte da costa atlântica portuguesa, na foz do Rio Minho, a poucos quilómetros de Caminha e da fronteira com a Galiza. A qualidade da água é Boa. O areal é extenso e as dunas que o enquadram são de grande dimensão — um dos sistemas dunares mais imponentes do litoral do Minho. A Ilha de Caminha, no estuário, e as colinas galegas visíveis do areal conferem ao lugar um horizonte duplo, entre o Atlântico e o estuário. É uma praia de chegada e de partida — o fim do litoral português antes da fronteira.' WHERE id = 'b699e6b6-e0cb-4620-9355-e1f3074ddde9';

UPDATE beaches SET description = 'A Praia de Ofir situa-se na margem norte da foz do Cávado, em Esposende, com dunas altas, pinhal dunar e uma costa atlântica de carácter selvagem que contrasta com o turismo mais organizado das praias a sul. A qualidade da água é Boa. As dunas de Ofir são das mais significativas do litoral norte — acumulações de areia que chegam a alturas consideráveis e que têm sido objeto de proteção por parte das autoridades ambientais. É uma praia com forte identidade de costa norte: vento, areia, pinheiros e o Atlântico a impor a sua escala.' WHERE id = 'dd37d1cd-8ecc-45af-b8d2-3ceabf881969';

UPDATE beaches SET description = 'A Praia do Cabedelo fica na margem sul da foz do Rio Lima, em Viana do Castelo, acessível de barco a partir da cidade ou por estrada pela margem sul. A qualidade da água é Boa. O areal é extenso e bem exposto ao Atlântico, com a cidade de Viana do Castelo visível do outro lado do estuário — a Basílica de Santa Luzia no horizonte é um dos enquadramentos mais reconhecíveis desta costa. A travessia de barco sobre o Lima faz parte da experiência de visitar a praia. É uma praia de identidade atlântica norte, com escala e qualidade que a tornam popular entre os habitantes da região.' WHERE id = '10f7f046-fb30-493e-acf0-bf6b2a57858b';

UPDATE beaches SET description = 'A Praia do Furadouro é a praia de Ovar — uma localidade com história piscatória que coexiste com o turismo balnear sazonal desta secção da costa norte. A qualidade da água é Boa. O areal é de dimensão generosa e a ondulação atlântica é constante, com condições que atraem surfistas. As tradições de Ovar — nomeadamente o Carnaval, mas também o azulejo e a gastronomia — têm expressão cultural que vai além da praia. É uma praia de costa atlântica norte com identidade de vila balnear consolidada, a sul de Aveiro e a norte de Espinho.' WHERE id = 'c63cbf17-1445-4697-aa21-a5b9dff08851';

UPDATE beaches SET description = 'Vila Praia de Âncora é uma das mais tranquilas localidades costeiras do litoral do Minho — um areal calmo e familiar, numa baía parcialmente resguardada que atenua a ondulação atlântica habitual nesta latitude. A qualidade da água é Boa. A vila tem escala humana e uma atmosfera de resort balnear discreto — jardins junto ao mar, peixe fresco e a praia de areia clara que se estende em frente. Para quem viaja pelo litoral do Alto Minho, é uma paragem com as características de uma vila de praia portuguesa de qualidade, sem a afluência de Viana do Castelo ou Caminha.' WHERE id = '43290bbc-db7f-4b1e-9cb5-a51b644c0ca6';

-- ═══════════════════════════════════════════════
-- OESTE (12)
-- ═══════════════════════════════════════════════

UPDATE beaches SET description = 'A Lagoa de Albufeira é uma laguna costeira a sul de Lisboa, separada do Atlântico por um cordão de areia que configura dois ambientes de banho distintos: o oceano aberto com ondulação franca, e a laguna de águas calmas e temperadas que aquecem mais rapidamente no verão. A qualidade da água é Boa. A coexistência dos dois ambientes num mesmo espaço é o principal atributo do lugar — e torna-o numa opção versátil para famílias com crianças pequenas. A zona é também frequentada por praticantes de windsurf e kitesurf nas sessões de vento sul.' WHERE id = 'e11188da-c19e-4c9d-a2a6-59f777412a05';

UPDATE beaches SET description = 'O Portinho da Arrábida é a praia da Arrábida por definição — uma enseada com água de tonalidade verde-esmeralda e azul-turquesa que deve a sua cor excecional ao calcário branco das falésias que rodeiam a baía. A qualidade da água é Boa. Insere-se no Parque Natural da Arrábida, o que limita o acesso de automóveis e contribui para preservar a qualidade do ambiente. O mergulho nas águas do Portinho é um dos mais ricos da costa portuguesa, com visibilidade e biodiversidade marinhas que raramente se encontram no litoral continental. É uma das praias mais extraordinárias de Portugal — a escassos quilómetros de Lisboa.' WHERE id = 'cb7d55ac-702f-49ec-98f7-d2c8c8e62715';

UPDATE beaches SET description = 'A Praia da Costa de Caparica é uma das mais extensas do litoral português — um areal que se prolonga por dezenas de quilómetros a sul de Lisboa, com cultura de surf enraizada, transportes regulares desde a capital e um carácter de destino balnear urbano que serve milhares de visitantes diariamente no verão. A qualidade da água é Boa. Cada secção da Caparica tem a sua identidade: do acesso norte mais familiar às zonas sul mais calmas, com as praias de surf a distribuírem-se ao longo de toda a extensão. É a praia de Lisboa por excelência — e um dos destinos balneares com melhor acessibilidade a partir da capital.' WHERE id = '49839927-ee16-498b-80a8-f029627fd4c5';

UPDATE beaches SET description = 'A Praia da Fonte da Telha situa-se a sul da Costa de Caparica, numa secção mais afastada dos acessos principais que lhe confere menor afluência e maior tranquilidade durante os meses de verão. A qualidade da água é Boa. O areal é contínuo com o extenso litoral da Caparica, com a mesma ondulação atlântica mas sem a densidade das zonas norte. A Mata Nacional dos Medos, que enquadra os acessos, é uma floresta dunar que reforça o carácter natural desta parte da costa. É uma alternativa para quem quer a Caparica com mais espaço de praia por pessoa.' WHERE id = '508706d1-2ddd-4377-8319-75a5bb347435';

UPDATE beaches SET description = 'A Praia das Maçãs fica no litoral de Sintra, numa localidade que ao longo de décadas preservou o carácter de vila balnear de pequena escala — com um elétrico histórico que desce de Sintra até à praia e confere ao percurso uma dimensão de experiência que vai além do balnear. A qualidade da água é Boa. O areal é de dimensão contida e a ondulação atlântica desta costa é franca — adequada para surf e bodyboard. A Praia das Maçãs é o ponto de chegada de uma costa que inclui praias como Azenhas do Mar e Magoito — cada uma com carácter próprio, todas dentro do enquadramento do Parque Natural de Sintra-Cascais.' WHERE id = 'd81736c8-0e7d-4d98-b369-377998fc5c2f';

UPDATE beaches SET description = 'A Praia de Carcavelos é a maior praia entre Lisboa e Cascais — um areal amplo com boas condições de surf, transportes directos desde o centro de Lisboa e um perfil que a tornaram no principal pólo de aprendizagem de surf da grande área da capital. A qualidade da água é Boa. A praia tem infraestrutura completa e uma animação de frente de mar que a distingue das praias mais tranquilas da linha. O Forte de São Julião da Barra — uma das fortalezas marítimas mais bem preservadas da costa portuguesa — avança para o mar numa extremidade da praia, conferindo-lhe uma dimensão histórica invulgar.' WHERE id = '406a09d1-daa7-44b3-aa19-3a13b4aab711';

UPDATE beaches SET description = 'Ericeira é a única Reserva Mundial de Surf da Europa — uma distinção que reconhece a qualidade e variedade de ondas concentradas num raio reduzido de costa, com breaks de referência ao longo do perímetro da vila. A qualidade da água é Boa. A vila piscatória de Ericeira, com o seu casco histórico pintado de azul e branco sobre a falésia, mantém carácter genuíno e uma gastronomia costeira de qualidade. É um destino que combina surf de nível mundial com vila histórica preservada — uma combinação rara no litoral europeu e que justifica a sua reputação internacional crescente.' WHERE id = '67e04297-3a9a-4e41-808f-cae811d0680b';

UPDATE beaches SET description = 'A Praia de S. Pedro do Estoril é uma das praias mais resguardadas da costa do Estoril — um areal de dimensão contida, parcialmente protegido pelo promontório adjacente, com acesso direto a partir da linha de comboio que corre entre Lisboa e Cascais. A qualidade da água é Boa. A escala da praia e o carácter relativamente tranquilo são os seus principais atributos — não tem a dimensão de Carcavelos nem a animação do Estoril, mas oferece uma opção de praia mais silenciosa nesta costa densamente servida. O enquadramento sobre a baía de Cascais é um dos mais agradáveis desta secção da linha.' WHERE id = '7b053b2b-f6f9-4d2b-b897-e4f4b52f463a';

UPDATE beaches SET description = 'A Praia do Guincho fica dentro do Parque Natural de Sintra-Cascais, a poucos quilómetros de Cascais, com uma exposição atlântica total que a torna uma das praias mais ventosas e selvagens da costa próxima de Lisboa. A qualidade da água é Boa. As condições de vento e ondulação fazem da praia um dos principais pontos de windsurf e kitesurf da Europa — o Guincho acolheu várias etapas de campeonatos mundiais. A paisagem envolvente — as dunas, as rochas e a Serra de Sintra ao fundo — é de uma beleza crua que contrasta com o ordenamento das praias urbanas da linha. Para desporto ou paisagem, é uma das praias com maior carácter de toda esta costa.' WHERE id = '8d29adfa-7276-4074-bce6-dc1c6b49ae12';

UPDATE beaches SET description = 'A Praia do Meco fica a sul da Costa de Caparica, numa secção do litoral onde o carácter natural começa a substituir a densidade urbana da Caparica. A qualidade da água é Boa. A praia é conhecida por ter uma das secções naturistas mais estabelecidas da costa de Lisboa. O areal é amplo e as falésias baixas que o enquadram criam algum resguardo. A distância aos transportes públicos contribui para menor afluência do que as praias ao norte. É uma praia de costa atlântica aberta, com o carácter das praias naturais do setubalino sem a celebridade das praias da Arrábida.' WHERE id = '4b7f7ece-a91f-4ef0-bd4f-f8f280a6b78a';

UPDATE beaches SET description = 'A Praia Grande fica no litoral de Sintra, num areal de nome que cumpre a promessa — é efectivamente grande: largo, extenso e exposto à ondulação atlântica desta secção da costa de Sintra-Cascais. A qualidade da água é Boa. A falésia adjacente contém pegadas de dinossauro preservadas nas rochas sedimentares — uma das ocorrências paleontológicas mais acessíveis ao público em Portugal. A ondulação torna-a popular para surf, e a escala do areal absorve bem a afluência de verão. É uma praia complementar à mais pequena Azenhas do Mar, a poucos minutos — dois formatos muito diferentes de praia no mesmo troço de costa.' WHERE id = '513d687d-b8f9-4d87-b5a7-c6de1d7d695c';

UPDATE beaches SET description = 'A Ribeira d''Ilhas é o break principal da Reserva Mundial de Surf de Ericeira — um point break que se estende ao longo de uma falésia baixa a norte da vila, criando condições que atraem surfistas de todo o mundo durante o inverno e a primavera. A qualidade da água é Boa. A praia tem carácter de surf destination: as tribunas naturais na falésia, a qualidade das ondas direitas e a concentração de surfistas experientes conferem-lhe uma energia diferente das praias de banho convencionais. Em dias de grande ondulação, é um dos espetáculos naturais mais impressionantes desta costa — acessível a pé da vila de Ericeira.' WHERE id = 'a9b0eada-8f04-4862-85aa-2892039baecd';
